version: "3.9"
services:
  #frontend-contoh:
  #  image: cilist-frontend:latest
  #  ports:
  #  - 3000:3000
  #  environment:
  #    REACT_APP_BACKEND_URL: "http://backend-contoh:5000"
    

  # backend-contoh:
  #   image: cilist-backend:latest
  #   ports:
  #     - 5000:5000
  #   environment:
  #     DATABASE_USERNAME: "people"
  #     DATABASE_PASSWORD: "people"
  #     DATABASE_DATABASE: "people" 
  #     DATABASE_HOST: "mysql-contoh"
  #     DATABASE_PORT: 3306
  #     BASE_URL_PORT: 5000
  #   depends_on:
  #     - mysql-contoh

  mysql-contoh:
    image: mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "favianhugo27"
      MYSQL_USER: "people"
      MYSQL_PASSWORD: "people"
      MYSQL_DATABASE: "people"
      MYSQL_HOST: "backend-contoh"
    volumes:
      - /database/crud_db.sql:/docker-entrypoint-initdb.d/crud_db.sql 

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080