FROM node:current-alpine3.17
#move files in current directory to app
COPY . /app/
# cd app
WORKDIR /app/
# cp environment
# RUN cp .env.example .env
#install dependencies
RUN npm install
#exposing backend
EXPOSE 5000
#running npm
CMD npm start
